setwd("C:/Users/RGAIKWAD/Desktop/R/")
raw<-read.csv("Reviews.csv")
dummy<-read.csv("Reviews.csv")
View(raw)
hist(raw$Age)
require(ggplot2)
ggplot(data=raw) + geom_bar(aes(x=raw$Rating, fill=raw$Recommended.IND))
summary(raw$Recommended.IND)
raw$Recommended.IND = as.factor(raw$Recommended.IND)
is.integer(raw$Recommended.IND)
library(tm)
raw_data<-Corpus(VectorSource(raw$Review.Text))
head(raw_data)
raw_data <- tm_map(raw_data, content_transformer(tolower))
raw_data <- tm_map(raw_data, removeNumbers)
raw_data <- tm_map(raw_data, removeWords, stopwords("english"))
raw_data <- tm_map(raw_data, removePunctuation)
raw_data <- tm_map(raw_data, stripWhitespace)
library(SnowballC)
raw_data <- tm_map(raw_data, stemDocument)
Doc_matrix<-TermDocumentMatrix(raw_data)
m<-as.matrix(Doc_matrix)
v<-sort(rowSums(m),decreasing = TRUE)
d<-data.frame(word = names(v),freq=v)
head(d,10)
library(wordcloud)
library(RColorBrewer)
par(bg="blue")
png(file="WordCloud.png",width=1000,height=700, bg="grey30")
wordcloud::wordcloud(d$word, d$freq, col=terrain.colors(length(d$word), alpha=0.9), random.order=FALSE, rot.per=0.3)
#wordcloud(d$word, d$freq, col=terrain.colors(length(d$word), alpha=0.9), random.order=FALSE, rot.per=0.3 )
title(main = "first word cloud", font.main = 1, col.main = "cornsilk3", cex.main = 1.5)
dev.off()

